image: mcr.microsoft.com/playwright:v1.56.1-jammy

stages:
  - monitor

monitor:
  stage: monitor

  before_script:
    - npm ci
    - npx playwright install --with-deps

  script:
    - node main.js
